### ISSUE TITLE
TF Symbolic returns variable "t" instead of "s"

### ISSUE THREAD

**Issue by OndrejBukovsky** [MatyasVasek/SymCirc#7]
**Describe the bug**
TF Symbolic returns variable "t" instead of "s"

**To Reproduce**
```python
# RLC
from symcirc import *
from importlib.metadata import version

print(f"Current version of Symcirc: {version('symcirc')}\n")

netlist = """

V1 1 0 DC 1 AC 1 0
R1 1 2 10
L1 2 3 1m
C1 3 0 10n

"""

circuit = AnalyseCircuit(netlist, "TF", symbolic=True, method="tableau")
results = circuit.node_voltages()
results.update(circuit.component_values("all"))

print(results)
```

**Output**
```
Current version of Symcirc: 0.1.1

{'v(1)': V1, 'v(2)': (C1*L1*V1*t**2 + V1)/(C1*L1*t**2 + C1*R1*t + 1), 'v(3)': V1/(C1*L1*t**2 + C1*R1*t + 1), 'v(V1)': V1, 'i(V1)': -C1*V1*t/(C1*L1*t**2 + C1*R1*t + 1), 'v(R1)': C1*R1*V1*t/(C1*L1*t**2 + C1*R1*t + 1), 'i(R1)': C1*V1*t/(C1*L1*t**2 + C1*R1*t + 1), 'v(L1)': C1*L1*V1*t**2/(C1*L1*t**2 + C1*R1*t + 1), 'i(L1)': C1*V1*t/(C1*L1*t**2 + C1*R1*t + 1), 'v(C1)': V1/(C1*L1*t**2 + C1*R1*t + 1), 'i(C1)': C1*V1*t/(C1*L1*t**2 + C1*R1*t + 1)}
```

**Comment by MatyasVasek** [comment]
Fixed, it was introduced by a typo in a previous code cleaning commit.

**Comment by OndrejBukovsky** [comment]
If you resolve any issues, please update the version number so I can build and install the new release. If you're working on something and prefer not to release a new version yet, just leave a comment on the corresponding issue, indicating that it will be fixed in version X.X.X, and I’ll wait. (If I change the number locally and you release the same version later. It'll be a mess)

**Comment by MatyasVasek** [comment]
Good point. I've uploaded version 0.1.2 on pypi. All tests ended successfully on my machine.
